name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  pull_request:
    paths:
      - 'charts/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and push Helm charts
        run: |
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              chart_name=$(basename "$chart")
              echo "Packaging chart: ${chart_name}"
              helm package "$chart"
              
              echo "Pushing chart: ${chart_name}"
              for i in {1..3}; do
                if helm push "${chart_name}"*.tgz oci://${{ env.REGISTRY }}/${{ env.OWNER }}/helm-charts; then
                  echo "Successfully pushed ${chart_name}"
                  break
                else
                  echo "Failed to push ${chart_name}, attempt $i"
                  if [ $i -eq 3 ]; then
                    echo "Failed to push ${chart_name} after 3 attempts"
                    exit 1
                  fi
                  sleep 5
                fi
              done
            fi
          done
